### PR TITLE
Various changes in the script

### PR DESCRIPTION
**Pull request by juan-morales**
Hello, I found your script and it was really usefull.

I decided to make some changes in order to refactor the code and also add some more features, and I wanted to share them with you. This little script is really usefull and demanded actually.

In the commits you can appreciate the messages about the changes I made.

I hope you let me add this personal touch to your project now and in the future.

Have a good day.

Juan

### CODE REVIEW

**Comment by juan-morales** [comment]
Any appreciation or observation is welcome too.

**Comment by hakoerber** [comment]
Hey, thank you for your contribution!

The code looks ok to me. I saw one small issue, see the review above.

Otherwise I have no problems merging this. Again, thank you very much!

**Comment by juan-morales** [comment]
you are welcome!

By the way ... where is the review you pointed me ( I am having a hard time looking for it ) ? So I can fix/change it


UPDATE:

I just applied some changes according to https://www.shellcheck.net/ to refactor the code a little bit too.

**Comment by hakoerber** [comment]
Hey!

I am not sure about the review... it should be in this discussion. Or in
the changes tab.

Nice idea about the shellcheck!

One more thing: If you want, you can do an interactive rebase to get rid of
the merge commit. No problem if you leave it as it is though.

I do not have a laptop currently, will get back to you on sunday or monday.

**Comment by juan-morales** [comment]
I still cannot find the code review :worried: , sorry for that. 

"shellcheck" definetly pointed some issues worth to fix. 

No worries, get back when you can. I will wait for your reply. 

Have a good weekend.

**Comment by hakoerber** [comment]
The review was about the repetition of the `ping` command, which you fixed in the meantime with the `execute_test` function.

So, everything looks good now!

Thank you very much for your contribution! Awesome work!

**Comment by juan-morales** [comment]
thanks to you too

**Pull request merged**
